### ISSUE TITLE
How to Generate APK with custom keystore

### ISSUE THREAD

**Issue by GoRaN909** [muhammadalkady/QuranHeritage-Android#1]
**As Salamualikum brother, God bless you for making this app i used you source code to create my own apk file to play online files from archive.org website and everything is works perfectly expect app signing with my created keystore file the apk is not build and i get failed Only i can export apk file with your keystore that you included in the source app folder!

Could you please help me and tell me how to fix that error and generate signed apk file with mine keystore?

Note: the app i created is an Quranic Audio Player app just like your but i added many other Quran reciters please i need some help from you bro.**

**Comment by muhammadalkady** [comment]
walaikum assalam wa rahmatullahi barakatuh
![Screenshot 2022-02-01 092526](https://user-images.githubusercontent.com/44714079/151928794-aebae368-b36b-49bb-9dba-350175d51272.png)
1- Create keystore file and save `storePassword`, `keyAlias `and `keyPassword`.
2- Change` build.gradle` keystore file path (`storeFile`), `storePassword ` , `keyAlias `and `keyPassword  `as in the above image
3- Generate the release APK.

**Comment by muhammadalkady** [comment]
I will close this issue for now.
If this didn't help please open it again.

**Comment by GoRaN909** [comment]
> walaikum assalam wa rahmatullahi barakatuh ![Screenshot 2022-02-01 092526](https://user-images.githubusercontent.com/44714079/151928794-aebae368-b36b-49bb-9dba-350175d51272.png) 1- Create keystore file and save `storePassword`, `keyAlias `and `keyPassword`. 2- Change` build.gradle` keystore file path (`storeFile`), `storePassword ` , `keyAlias `and `keyPassword `as in the above image 3- Generate the release APK.

I'm sorry for late and Thank you for replay bro i did that like yours before but i doesn't works when i create a new keystore file the type of key is .jks it does not like yours, Your keystore type is just File no like the one that support in Android studio .jks file this error happens when i change the package name from yours to another one the app is not build not debug and release variant :( 

here is the screenshot of it: 

[![Screenshot-2022-02-04-013410.png](https://i.postimg.cc/LsyqXV9V/Screenshot-2022-02-04-013410.png)](https://postimg.cc/GBy3gGsB)

**Comment by GoRaN909** [comment]
> walaikum assalam wa rahmatullahi barakatuh ![Screenshot 2022-02-01 092526](https://user-images.githubusercontent.com/44714079/151928794-aebae368-b36b-49bb-9dba-350175d51272.png) 1- Create keystore file and save `storePassword`, `keyAlias `and `keyPassword`. 2- Change` build.gradle` keystore file path (`storeFile`), `storePassword ` , `keyAlias `and `keyPassword `as in the above image 3- Generate the release APK.

I'm sorry for late,  Bro @muhammadalkady Thank your for replay bro i did that like yours before but i doesn't works when i create a new keystore file the type of key is .jks it does not like yours, Your keystore type is just File no like the one that support in Android studio .jks file this error happens when i change the package name from yours to another one the app is not build not debug and release variant :( 

here is the screenshot of it: 

[![Screenshot-2022-02-04-013410.png](https://i.postimg.cc/LsyqXV9V/Screenshot-2022-02-04-013410.png)](https://postimg.cc/GBy3gGsB)

**Comment by GoRaN909** [comment]
My created keystore file path is in the same folder just like yours placed in 

[![Screenshot-2022-02-04-014339.png](https://i.postimg.cc/j2BPj4h1/Screenshot-2022-02-04-014339.png)](https://postimg.cc/bSHsCbW0)
